# ----------------------------------------
# Created on: Tue Jul  2 14:58:09 2024
# Auto generated by Pango
# ----------------------------------------

vlib  work
vmap  work ./work
vmap  usim "D:/pango/pango_sim_libraries/usim"
vmap  adc "D:/pango/pango_sim_libraries/adc"
vmap  ddrc "D:/pango/pango_sim_libraries/ddrc"
vmap  ddrphy "D:/pango/pango_sim_libraries/ddrphy"
vmap  hsst_e2 "D:/pango/pango_sim_libraries/hsst_e2"
vmap  iolhr_dft "D:/pango/pango_sim_libraries/iolhr_dft"
vmap  ipal_e1 "D:/pango/pango_sim_libraries/ipal_e1"
vmap  pciegen2 "D:/pango/pango_sim_libraries/pciegen2"
vlog -work work   \
"D:/pango/MyProject/oscillosope/rtl/adc_rd.v" \
"D:/pango/MyProject/oscillosope/rtl/data_packing.v" \
"D:/pango/MyProject/oscillosope/rtl/encoder_drive.v" \
"D:/pango/MyProject/oscillosope/rtl/f_Sa_control.v" \
"D:/pango/MyProject/oscillosope/rtl/fifo_rd.v" \
"D:/pango/MyProject/oscillosope/rtl/fifo_wr.v" \
"D:/pango/MyProject/oscillosope/rtl/ip_fifo.v" \
"D:/pango/MyProject/oscillosope/rtl/key_debounce.v" \
"D:/pango/MyProject/oscillosope/rtl/my_spi_drive.v" \
"D:/pango/MyProject/oscillosope/rtl/state_control.v" \
"D:/pango/MyProject/oscillosope/rtl/top_module.v" \
"D:/pango/MyProject/oscillosope/rtl/force_trig.v" \
"D:/pango/MyProject/oscillosope/rtl/f_measure.v" \
"D:/pango/MyProject/oscillosope/rtl/divider_32.v" \
"D:/pango/MyProject/oscillosope/rtl/output_shaping.v" \
"D:/pango/MyProject/oscillosope/prj/ipcore/pll_clk/pll_clk.v" \
"D:/pango/MyProject/oscillosope/prj/ipcore/async_fifo/rtl/ipml_fifo_ctrl_v1_4_async_fifo.v" \
"D:/pango/MyProject/oscillosope/prj/ipcore/async_fifo/rtl/ipml_sdpram_v1_6_async_fifo.v" \
"D:/pango/MyProject/oscillosope/prj/ipcore/async_fifo/rtl/ipml_fifo_v1_7_async_fifo.v" \
"D:/pango/MyProject/oscillosope/prj/ipcore/async_fifo/async_fifo.v" \
"D:/pango/MyProject/oscillosope/sim/tb/top_module_tb.v" 

# ----------------------------------------
